version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    pull-request-branch-name:
      separator: '-'
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: 'direct'
    reviewers:
      - 'theo-mesnil'
